### PR TITLE
jdbc urls for pdo

### PR DESCRIPTION
**Pull request by terefang**

### CODE REVIEW

**Comment by Kdecherf** [comment]
Just a question : What is the utility of the 'pdo.properties' file ?

**Comment by terefang** [comment]
to keep code clean it maps jdbc driver tags to driver classes, could be moved to meta-inf if you like

**Comment by Kdecherf** [comment]
Okay great :)

I think it can be moved to WEB-INF

**Comment by terefang** [comment]
for the user to administer ? -- bad idea.

or yet better moving defaults to meta-inf in the jar and let the user customize this with php.ini vars like:

pdo.jdbc.h2.class = org.h2.Driver

would that make sense ?

**Comment by Kdecherf** [comment]
Hmm okay, we keep it in the package folder and we give the ability to user to change properties via php.ini

**Pull request merged**
